// src/redux/types/connectionTypes.js

// User search action types
export const SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST";
export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_FAILURE = "SEARCH_USERS_FAILURE";

// Add connection action types
export const ADD_CONNECTION_REQUEST = "ADD_CONNECTION_REQUEST";
export const ADD_CONNECTION_SUCCESS = "ADD_CONNECTION_SUCCESS";
export const ADD_CONNECTION_FAILURE = "ADD_CONNECTION_FAILURE";

// Fetch connections action types
export const FETCH_CONNECTIONS_REQUEST = "FETCH_CONNECTIONS_REQUEST";
export const FETCH_CONNECTIONS_SUCCESS = "FETCH_CONNECTIONS_SUCCESS";
export const FETCH_CONNECTIONS_FAILURE = "FETCH_CONNECTIONS_FAILURE";

// Connection response action types
export const ACCEPT_CONNECTION_REQUEST = "ACCEPT_CONNECTION_REQUEST";
export const ACCEPT_CONNECTION_SUCCESS = "ACCEPT_CONNECTION_SUCCESS";
export const ACCEPT_CONNECTION_FAILURE = "ACCEPT_CONNECTION_FAILURE";

export const REJECT_CONNECTION_REQUEST = "REJECT_CONNECTION_REQUEST";
export const REJECT_CONNECTION_SUCCESS = "REJECT_CONNECTION_SUCCESS";
export const REJECT_CONNECTION_FAILURE = "REJECT_CONNECTION_FAILURE";

// Set relevant data types
export const SET_CAREGIVER_DATA = "SET_CAREGIVER_DATA";
export const SET_PATIENT_DATA = "SET_PATIENT_DATA";
